name: Sync NVIDIA Images to Docker Hub

on:
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - src: nvcr.io/nvidia/tritonserver:24.05-py3
            dst: lokeshkurre/tritonserver:24.05-py3
          - src: nvcr.io/nvidia/tritonserver:24.05-py3-sdk
            dst: lokeshkurre/tritonserver:24.05-py3-sdk
          - src: nvcr.io/nvidia/tritonserver:24.05-py3-min
            dst: lokeshkurre/tritonserver:24.05-py3-min
          - src: nvcr.io/nvidia/tensorrt:24.05-py3
            dst: lokeshkurre/tensorrt:24.05-py3
    steps:
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u lokeshkurre --password-stdin

      - name: Pull, Tag, and Push
        run: |
          docker pull ${{ matrix.src }}
          docker tag ${{ matrix.src }} ${{ matrix.dst }}
          docker push ${{ matrix.dst }}
